MERGE INTO ROLES (NAME, DESCRIPTION) KEY(NAME) VALUES ('SUPERADMIN', 'Super administrator');
MERGE INTO ROLES (NAME, DESCRIPTION) KEY(NAME) VALUES ('ADMIN', 'Administrator');
MERGE INTO ROLES (NAME, DESCRIPTION) KEY(NAME) VALUES ('USUARIO', 'Default application user');
