package com.springboot.MyTodoList.agent;

public enum IntentType {
    HELP,
    LIST_TASKS,
    LIST_TASKS_BY_ASSIGNEE,
    LIST_TASKS_BY_STATUS,
    LIST_TASKS_BY_SPRINT,
    CREATE_TASK,
    START_TASK,
    COMPLETE_TASK,
    REOPEN_TASK,
    DELETE_TASK,
    CURRENT_SPRINT_SUMMARY,
    TEAM_LOAD_SUMMARY,
    GUACAMOLE_RECIPE,
    UNKNOWN
}
