#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
backend_dir="$repo_root/MtdrSpring/backend"
env_file="$backend_dir/.env.local"
template_file="$backend_dir/.env.example"

ask_value() {
  local prompt_text="$1"
  local default_value="${2:-}"
  local response=""

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt_text [$default_value]: " response
    printf '%s' "${response:-$default_value}"
  else
    read -r -p "$prompt_text: " response
    printf '%s' "$response"
  fi
}

ask_secret() {
  local prompt_text="$1"
  local response=""
  read -r -s -p "$prompt_text: " response
  echo
  printf '%s' "$response"
}

mkdir -p "$backend_dir"

profile="$(ask_value "Perfil para local (local/oracle)" "local")"
profile="${profile,,}"
if [[ "$profile" != "local" && "$profile" != "oracle" ]]; then
  echo "Perfil inválido: $profile"
  exit 1
fi

jwt_secret="$(ask_secret "JWT secret")"
ui_username="$(ask_value "Usuario UI" "admin")"
ui_password="$(ask_secret "Password UI")"
telegram_bot_token="$(ask_value "Telegram bot token (opcional)" "")"
telegram_bot_name="$(ask_value "Telegram bot name (opcional)" "")"
deepseek_api_key="$(ask_value "DeepSeek API key (opcional)" "")"
deepseek_api_url="$(ask_value "DeepSeek API URL" "https://api.deepseek.com/v1/chat/completions")"

db_user=""
dbpassword=""
db_url=""
driver_class_name=""
wallet_source=""

if [[ "$profile" == "oracle" ]]; then
  db_user="$(ask_value "Oracle db user")"
  dbpassword="$(ask_secret "Oracle db password")"
  db_url="$(ask_value "Oracle jdbc url" "jdbc:oracle:thin:@REPLACE_DB_SERVICE?TNS_ADMIN=/mtdrworkshop/creds")"
  driver_class_name="$(ask_value "Driver class name" "oracle.jdbc.OracleDriver")"
  wallet_source="$(ask_value "Ruta al wallet Oracle (dejar vacío si no lo vas a copiar ahora)" "")"

  if [[ -n "$wallet_source" ]]; then
    if [[ -d "$wallet_source" ]]; then
      mkdir -p "$backend_dir/wallet"
      rm -rf "$backend_dir/wallet"/*
      cp -R "$wallet_source"/. "$backend_dir/wallet"/
    else
      echo "Aviso: la ruta del wallet no existe, se dejará documentada pero no copiada."
    fi
  fi
fi

cat > "$env_file" <<EOF
# Generated by ./setup.sh
SPRING_PROFILES_ACTIVE=$profile

JWT_SECRET=$jwt_secret
TELEGRAM_BOT_TOKEN=$telegram_bot_token
TELEGRAM_BOT_NAME=$telegram_bot_name
DEEPSEEK_API_KEY=$deepseek_api_key
DEEPSEEK_API_URL=$deepseek_api_url

ui_username=$ui_username
ui_password=$ui_password

db_user=$db_user
dbpassword=$dbpassword
db_url=$db_url
driver_class_name=$driver_class_name
EOF

echo ""
echo "Configuración escrita en $env_file"
if [[ "$profile" == "oracle" ]]; then
  echo "Wallet Oracle: usa backend/wallet/ en runtime o monta el secreto correspondiente."
else
  echo "Perfil local listo: no se requiere wallet para H2."
fi
