apiVersion: v1
kind: Service
metadata:
  name: todolistapp-springboot-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local

  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: todolistapp-springboot
---
#this is new stuff for hosting on the load balancer
apiVersion: v1
kind: Service
metadata:
  name: todolistapp-backend-router
spec:
  selector:
    app: todolistapp-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp-springboot-deployment
spec:
  selector:
    matchLabels:
      app: todolistapp-springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: todolistapp-springboot
        version: v1
    spec:
      containers:
        - name: todolistapp-springboot
          image: mx-queretaro-1.ocir.io/axdispqrsjop/reacttodo/v7rzn/todolistapp-springboot:0.1
          imagePullPolicy: Always
          env:
            - name: db_user
              value: "ADMIN"
            - name: db_url
              value: "jdbc:oracle:thin:@reacttodok7toc_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: todo.table.name
              value: "todoitem"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "mx-queretaro-1"
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: true
            - name: ui_username
              value: "admin"
            - name: TELEGRAM_BOT_TOKEN2
              value: "8039852029:AAGZyNJMzZQBHlwi_3FNLSNc2mwgCtOhwrs"
            - name: TELEGRAM_BOT_TOKEN
              value: "8650008700:AAHADZmPDY4a3zpdcRT8Hwv54b1hgf8Cjbs"
            - name: ui_password
              valueFrom:
                secretKeyRef:
                  name: frontendadmin
                  key: password
                  optional: true
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: todolistapp-springboot
---
apiVersion: v1
kind: Namespace
metadata:
  name: p7-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: p7frontend-service
  namespace: p7-frontend
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local

  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: p7frontend
---
# this is new stuff for hosting on the load balancer
apiVersion: v1
kind: Service
metadata:
  name: p7frontend-router
  namespace: p7-frontend
spec:
  selector:
    app: p7frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p7frontend-deployment
  namespace: p7-frontend
spec:
  selector:
    matchLabels:
      app: p7frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: p7frontend
        version: v1
    spec:
      imagePullSecrets:
        - name: oci-registry-secret
      containers:
        - name: p7frontend
          image: mx-queretaro-1.ocir.io/axdispqrsjop/equipo52/yv0fi/p7frontend:latest
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "__BACKEND_API_URL__"
            - name: NODE_ENV
              value: "production"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
      restartPolicy: Always
