name: Lint Code Base

on:
  push:
    branches: [develop]   # solo develop directo
  pull_request:
    branches: [main, develop]  # PRs a ambas

jobs:
  super-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # 🔥 clave para performance
          VALIDATE_ALL_CODEBASE: false